export enum Role {
  // Direção
  diretor_geral = 'diretor_geral',
  diretor_clinico = 'diretor_clinico',
  diretor_enfermagem = 'diretor_enfermagem',
  diretor_financeiro = 'diretor_financeiro',
  diretor_operacional = 'diretor_operacional',
  diretor_rh = 'diretor_rh',
  diretor_ti = 'diretor_ti',
  diretor_qualidade = 'diretor_qualidade',
  // Clínico — Médicos
  medico = 'medico',
  medico_especialista = 'medico_especialista',
  cirurgiao = 'cirurgiao',
  anestesiologista = 'anestesiologista',
  radiologista = 'radiologista',
  patologista = 'patologista',
  // Clínico — Enfermagem
  enfermeiro = 'enfermeiro',
  enfermeiro_especialista = 'enfermeiro_especialista',
  enfermeiro_gestor = 'enfermeiro_gestor',
  // Clínico — Outros
  auxiliar_saude = 'auxiliar_saude',
  tecnico = 'tecnico',
  fisioterapeuta = 'fisioterapeuta',
  terapeuta_fala = 'terapeuta_fala',
  nutricionista = 'nutricionista',
  psicologo = 'psicologo',
  // Farmácia
  farmaceutico = 'farmaceutico',
  farmaceutico_clinico = 'farmaceutico_clinico',
  tecnico_farmacia = 'tecnico_farmacia',
  // Administrativo
  rececionista = 'rececionista',
  secretario_clinico = 'secretario_clinico',
  assistente_administrativo = 'assistente_administrativo',
  gestor_agendamento = 'gestor_agendamento',
  faturacao = 'faturacao',
  rh = 'rh',
  compras = 'compras',
  // Operacional
  maqueiro = 'maqueiro',
  assistente_operacional = 'assistente_operacional',
  esterilizacao = 'esterilizacao',
  limpeza = 'limpeza',
  lavandaria = 'lavandaria',
  // Engenharia / TI / Compliance
  engenheiro_biomedico = 'engenheiro_biomedico',
  tecnico_manutencao = 'tecnico_manutencao',
  seguranca = 'seguranca',
  sst = 'sst',
  it_admin = 'it_admin',
  analista_sistemas = 'analista_sistemas',
  dba = 'dba',
  ciberseguranca = 'ciberseguranca',
  bi_analyst = 'bi_analyst',
  dpo = 'dpo',
  gestor_qualidade = 'gestor_qualidade',
  compliance_officer = 'compliance_officer',
  controlo_infecao = 'controlo_infecao',
  auditor_interno = 'auditor_interno',
  // Legado (compatibilidade)
  auxiliar = 'auxiliar',
  administrativo = 'administrativo',
  chefe_turno = 'chefe_turno',
  chefe_enfermeiros = 'chefe_enfermeiros',
  chefe_medicos = 'chefe_medicos',
  triador = 'triador',
  anestesista = 'anestesista',
  instrumentista = 'instrumentista',
  secretaria = 'secretaria',
}

export enum SubRole {
  // Direção
  ceo_hospitalar = 'ceo_hospitalar',
  diretor_medico = 'diretor_medico',
  head_nurse = 'head_nurse',
  cfo = 'cfo',
  coo = 'coo',
  hr_director = 'hr_director',
  cio = 'cio',
  compliance_director = 'compliance_director',
  // Médico
  clinico_geral = 'clinico_geral',
  // Médico Especialista
  cardiologista = 'cardiologista',
  urologista = 'urologista',
  ortopedista = 'ortopedista',
  neurologista = 'neurologista',
  ginecologista = 'ginecologista',
  pediatra = 'pediatra',
  oncologista = 'oncologista',
  // Cirurgião / Anestesiologista
  cirurgiao_geral = 'cirurgiao_geral',
  medico_anestesia = 'medico_anestesia',
  // Imagiologia / Lab
  medico_imagem = 'medico_imagem',
  anatomia_patologica = 'anatomia_patologica',
  // Enfermeiro
  generalista = 'generalista',
  // Enfermeiro Especialista
  enf_uci = 'enf_uci',
  enf_bloco = 'enf_bloco',
  enf_obstetricia = 'enf_obstetricia',
  enf_pediatria = 'enf_pediatria',
  // Enfermeiro Gestor
  supervisor_enfermagem = 'supervisor_enfermagem',
  // Auxiliar de Saúde
  tae = 'tae',
  // Técnico
  tecnico_radiologia = 'tecnico_radiologia',
  tecnico_tac_rm = 'tecnico_tac_rm',
  tecnico_analises_clinicas = 'tecnico_analises_clinicas',
  tecnico_cardiopneumologia = 'tecnico_cardiopneumologia',
  // Outros clínicos
  reabilitacao_fisica = 'reabilitacao_fisica',
  reabilitacao_fala = 'reabilitacao_fala',
  nutricao_clinica = 'nutricao_clinica',
  psicologia_clinica = 'psicologia_clinica',
  // Farmácia
  farmaceutico_hospitalar = 'farmaceutico_hospitalar',
  farmaceutico_oncologico = 'farmaceutico_oncologico',
  tecnico_farmacia_assist = 'tecnico_farmacia_assist',
  // Administrativo
  front_desk = 'front_desk',
  secretariado = 'secretariado',
  backoffice = 'backoffice',
  scheduling = 'scheduling',
  billing_officer = 'billing_officer',
  hr_specialist = 'hr_specialist',
  procurement = 'procurement',
  // Operacional
  transporte_interno = 'transporte_interno',
  apoio_geral = 'apoio_geral',
  cssd = 'cssd',
  higiene_hospitalar = 'higiene_hospitalar',
  gestao_textil = 'gestao_textil',
  // Engenharia / TI
  equipamentos_medicos = 'equipamentos_medicos',
  facilities = 'facilities',
  vigilancia = 'vigilancia',
  seguranca_trabalho = 'seguranca_trabalho',
  sysadmin = 'sysadmin',
  his_erp = 'his_erp',
  database_admin = 'database_admin',
  security_officer = 'security_officer',
  dados_clinicos = 'dados_clinicos',
  // Compliance
  dpo_role = 'dpo_role',
  quality_manager = 'quality_manager',
  compliance = 'compliance',
  infection_control = 'infection_control',
  internal_audit = 'internal_audit',
}

export const SUBROLES_POR_ROLE: Partial<Record<Role, SubRole[]>> = {
  [Role.diretor_geral]: [SubRole.ceo_hospitalar],
  [Role.diretor_clinico]: [SubRole.diretor_medico],
  [Role.diretor_enfermagem]: [SubRole.head_nurse],
  [Role.diretor_financeiro]: [SubRole.cfo],
  [Role.diretor_operacional]: [SubRole.coo],
  [Role.diretor_rh]: [SubRole.hr_director],
  [Role.diretor_ti]: [SubRole.cio],
  [Role.diretor_qualidade]: [SubRole.compliance_director],
  [Role.medico]: [SubRole.clinico_geral],
  [Role.medico_especialista]: [
    SubRole.cardiologista, SubRole.urologista, SubRole.ortopedista,
    SubRole.neurologista, SubRole.ginecologista, SubRole.pediatra, SubRole.oncologista,
  ],
  [Role.cirurgiao]: [SubRole.cirurgiao_geral],
  [Role.anestesiologista]: [SubRole.medico_anestesia],
  [Role.radiologista]: [SubRole.medico_imagem],
  [Role.patologista]: [SubRole.anatomia_patologica],
  [Role.enfermeiro]: [SubRole.generalista],
  [Role.enfermeiro_especialista]: [
    SubRole.enf_uci, SubRole.enf_bloco, SubRole.enf_obstetricia, SubRole.enf_pediatria,
  ],
  [Role.enfermeiro_gestor]: [SubRole.supervisor_enfermagem],
  [Role.auxiliar_saude]: [SubRole.tae],
  [Role.tecnico]: [
    SubRole.tecnico_radiologia, SubRole.tecnico_tac_rm,
    SubRole.tecnico_analises_clinicas, SubRole.tecnico_cardiopneumologia,
  ],
  [Role.fisioterapeuta]: [SubRole.reabilitacao_fisica],
  [Role.terapeuta_fala]: [SubRole.reabilitacao_fala],
  [Role.nutricionista]: [SubRole.nutricao_clinica],
  [Role.psicologo]: [SubRole.psicologia_clinica],
  [Role.farmaceutico]: [SubRole.farmaceutico_hospitalar],
  [Role.farmaceutico_clinico]: [SubRole.farmaceutico_oncologico],
  [Role.tecnico_farmacia]: [SubRole.tecnico_farmacia_assist],
  [Role.rececionista]: [SubRole.front_desk],
  [Role.secretario_clinico]: [SubRole.secretariado],
  [Role.assistente_administrativo]: [SubRole.backoffice],
  [Role.gestor_agendamento]: [SubRole.scheduling],
  [Role.faturacao]: [SubRole.billing_officer],
  [Role.rh]: [SubRole.hr_specialist],
  [Role.compras]: [SubRole.procurement],
  [Role.maqueiro]: [SubRole.transporte_interno],
  [Role.assistente_operacional]: [SubRole.apoio_geral],
  [Role.esterilizacao]: [SubRole.cssd],
  [Role.limpeza]: [SubRole.higiene_hospitalar],
  [Role.lavandaria]: [SubRole.gestao_textil],
  [Role.engenheiro_biomedico]: [SubRole.equipamentos_medicos],
  [Role.tecnico_manutencao]: [SubRole.facilities],
  [Role.seguranca]: [SubRole.vigilancia],
  [Role.sst]: [SubRole.seguranca_trabalho],
  [Role.it_admin]: [SubRole.sysadmin],
  [Role.analista_sistemas]: [SubRole.his_erp],
  [Role.dba]: [SubRole.database_admin],
  [Role.ciberseguranca]: [SubRole.security_officer],
  [Role.bi_analyst]: [SubRole.dados_clinicos],
  [Role.dpo]: [SubRole.dpo_role],
  [Role.gestor_qualidade]: [SubRole.quality_manager],
  [Role.compliance_officer]: [SubRole.compliance],
  [Role.controlo_infecao]: [SubRole.infection_control],
  [Role.auditor_interno]: [SubRole.internal_audit],
};

export const DEPARTAMENTO_POR_SUBROLE: Record<SubRole, string> = {
  [SubRole.ceo_hospitalar]: 'Administração',
  [SubRole.diretor_medico]: 'Direção Clínica',
  [SubRole.head_nurse]: 'Enfermagem',
  [SubRole.cfo]: 'Financeiro',
  [SubRole.coo]: 'Operações',
  [SubRole.hr_director]: 'Recursos Humanos',
  [SubRole.cio]: 'Tecnologia',
  [SubRole.compliance_director]: 'Qualidade',
  [SubRole.clinico_geral]: 'Medicina',
  [SubRole.cardiologista]: 'Cardiologia',
  [SubRole.urologista]: 'Urologia',
  [SubRole.ortopedista]: 'Ortopedia',
  [SubRole.neurologista]: 'Neurologia',
  [SubRole.ginecologista]: 'Ginecologia',
  [SubRole.pediatra]: 'Pediatria',
  [SubRole.oncologista]: 'Oncologia',
  [SubRole.cirurgiao_geral]: 'Bloco Operatório',
  [SubRole.medico_anestesia]: 'Bloco Operatório',
  [SubRole.medico_imagem]: 'Imagiologia',
  [SubRole.anatomia_patologica]: 'Laboratório',
  [SubRole.generalista]: 'Enfermagem',
  [SubRole.enf_uci]: 'Cuidados Intensivos',
  [SubRole.enf_bloco]: 'Cirurgia',
  [SubRole.enf_obstetricia]: 'Maternidade',
  [SubRole.enf_pediatria]: 'Pediatria',
  [SubRole.supervisor_enfermagem]: 'Gestão Enfermagem',
  [SubRole.tae]: 'Apoio Clínico',
  [SubRole.tecnico_radiologia]: 'Imagiologia',
  [SubRole.tecnico_tac_rm]: 'Imagiologia',
  [SubRole.tecnico_analises_clinicas]: 'Laboratório',
  [SubRole.tecnico_cardiopneumologia]: 'Diagnóstico',
  [SubRole.reabilitacao_fisica]: 'Terapias',
  [SubRole.reabilitacao_fala]: 'Terapias',
  [SubRole.nutricao_clinica]: 'Nutrição',
  [SubRole.psicologia_clinica]: 'Apoio ao Doente',
  [SubRole.farmaceutico_hospitalar]: 'Farmácia',
  [SubRole.farmaceutico_oncologico]: 'Farmácia',
  [SubRole.tecnico_farmacia_assist]: 'Farmácia',
  [SubRole.front_desk]: 'Atendimento',
  [SubRole.secretariado]: 'Consultas',
  [SubRole.backoffice]: 'Administração',
  [SubRole.scheduling]: 'Operações',
  [SubRole.billing_officer]: 'Financeiro',
  [SubRole.hr_specialist]: 'RH',
  [SubRole.procurement]: 'Supply Chain',
  [SubRole.transporte_interno]: 'Operações',
  [SubRole.apoio_geral]: 'Operações',
  [SubRole.cssd]: 'Central Esterilização',
  [SubRole.higiene_hospitalar]: 'Facilities',
  [SubRole.gestao_textil]: 'Facilities',
  [SubRole.equipamentos_medicos]: 'Engenharia',
  [SubRole.facilities]: 'Infraestruturas',
  [SubRole.vigilancia]: 'Segurança',
  [SubRole.seguranca_trabalho]: 'Compliance',
  [SubRole.sysadmin]: 'TI',
  [SubRole.his_erp]: 'TI',
  [SubRole.database_admin]: 'TI',
  [SubRole.security_officer]: 'TI',
  [SubRole.dados_clinicos]: 'Analytics',
  [SubRole.dpo_role]: 'Compliance',
  [SubRole.quality_manager]: 'Qualidade',
  [SubRole.compliance]: 'Jurídico',
  [SubRole.infection_control]: 'Segurança Clínica',
  [SubRole.internal_audit]: 'Qualidade',
};

export enum Servico {
  internamento = 'internamento',
  urgencia = 'urgencia',
  bloco_operatorio = 'bloco_operatorio',
  consultas_externas = 'consultas_externas',
  farmacia = 'farmacia',
  fisioterapia = 'fisioterapia',
  transporte = 'transporte',
  administrativo = 'administrativo',
}

export enum EstadoDoente {
  estavel = 'estavel',
  grave = 'grave',
  critico = 'critico',
  alta_prevista = 'alta_prevista',
}

export enum EstadoCama {
  livre = 'livre',
  ocupada = 'ocupada',
  em_limpeza = 'em_limpeza',
  reservada = 'reservada',
}

export enum TipoTarefa {
  clinica = 'clinica',
  logistica = 'logistica',
}

export enum PrioridadeTarefa {
  baixa = 'baixa',
  media = 'media',
  alta = 'alta',
  urgente = 'urgente',
}

export enum EstadoTarefa {
  pendente = 'pendente',
  em_progresso = 'em_progresso',
  concluida = 'concluida',
  cancelada = 'cancelada',
}

export enum TipoTurno {
  manha = 'manha',
  tarde = 'tarde',
  noite = 'noite',
}
