// Subset representativo de códigos ICD-10-CM para diagnósticos hospitalares comuns
export const ICD10_CODES: Record<string, string> = {
  // Doenças infecciosas
  'A40.0': 'Septicemia por Streptococcus grupo A',
  'A40.1': 'Septicemia por Streptococcus grupo B',
  'A40.3': 'Septicemia por Streptococcus pneumoniae',
  'A41.0': 'Septicemia por Staphylococcus aureus',
  'A41.1': 'Septicemia por outros Staphylococcus',
  'A41.51': 'Septicemia por Escherichia coli',
  'A41.9': 'Septicemia não especificada',
  'A48.3': 'Síndrome do choque tóxico',
  'B34.2': 'Infecção por coronavírus não especificada',
  'J12.82': 'Pneumonia por coronavírus',
  // Doenças respiratórias
  'J06.9': 'Infecção aguda do trato respiratório superior não especificada',
  'J18.1': 'Pneumonia lobar não especificada',
  'J18.9': 'Pneumonia não especificada',
  'J20.9': 'Bronquite aguda não especificada',
  'J22': 'Infecção aguda do trato respiratório inferior não especificada',
  'J44.0': 'DPOC com infecção respiratória aguda',
  'J44.1': 'DPOC com exacerbação aguda',
  'J45.20': 'Asma ligeira intermitente não complicada',
  'J45.40': 'Asma moderada persistente não complicada',
  'J45.50': 'Asma grave persistente não complicada',
  'J46': 'Estado de mal asmático',
  'J80': 'Síndrome da angústia respiratória aguda',
  'J96.00': 'Insuficiência respiratória aguda, hipoxémica',
  'J96.10': 'Insuficiência respiratória crónica não especificada',
  // Doenças cardiovasculares
  'I10': 'Hipertensão essencial (primária)',
  'I21.0': 'Enfarte agudo do miocárdio da parede anterior',
  'I21.1': 'Enfarte agudo do miocárdio da parede inferior',
  'I21.9': 'Enfarte agudo do miocárdio não especificado',
  'I22.9': 'Enfarte do miocárdio subsequente não especificado',
  'I24.9': 'Doença isquémica coronária aguda não especificada',
  'I25.10': 'Doença cardíaca aterosclerótica não especificada',
  'I26.99': 'Embolia pulmonar sem cor pulmonale agudo',
  'I35.0': 'Estenose da válvula aórtica',
  'I38': 'Endocardite de válvula não especificada',
  'I42.0': 'Cardiomiopatia dilatada',
  'I48.0': 'Fibrilhação auricular paroxística',
  'I48.11': 'Flutter auricular típico',
  'I48.19': 'Outras fibrilhações auriculares persistentes',
  'I50.20': 'Insuficiência cardíaca sistólica não especificada',
  'I50.30': 'Insuficiência cardíaca diastólica não especificada',
  'I50.9': 'Insuficiência cardíaca não especificada',
  'I63.9': 'Acidente vascular cerebral isquémico não especificado',
  'I64': 'Acidente vascular cerebral não especificado como hemorrágico ou isquémico',
  // Doenças digestivas
  'K25.0': 'Úlcera gástrica aguda com hemorragia',
  'K26.0': 'Úlcera duodenal aguda com hemorragia',
  'K35.2': 'Apendicite aguda com peritonite generalizada',
  'K40.30': 'Hérnia inguinal unilateral com obstrução, sem gangrena',
  'K57.30': 'Doença diverticular do intestino grosso sem abcesso',
  'K70.30': 'Cirrose alcoólica do fígado sem ascite',
  'K72.00': 'Insuficiência hepática aguda sem coma',
  'K80.10': 'Cálculo da vesícula biliar sem colecistite aguda',
  'K81.0': 'Colecistite aguda',
  'K85.9': 'Pancreatite aguda não especificada',
  'K86.1': 'Outras pancreatites crónicas',
  // Doenças endócrinas e metabólicas
  'E10.10': 'Diabetes mellitus tipo 1 com cetoacidose sem coma',
  'E11.00': 'Diabetes mellitus tipo 2 com hiperosmolaridade sem coma',
  'E11.40': 'Diabetes mellitus tipo 2 com neuropatia diabética não especificada',
  'E11.51': 'Diabetes mellitus tipo 2 com retinopatia diabética proliferativa',
  'E11.65': 'Diabetes mellitus tipo 2 com hiperglicemia',
  'E11.9': 'Diabetes mellitus tipo 2 sem complicações',
  'E87.1': 'Hiposmolaridade e hiponatremia',
  'E87.2': 'Acidose',
  'E87.3': 'Alcalose',
  'E87.5': 'Hiperpotassemia',
  'E87.6': 'Hipopotassemia',
  // Doenças renais
  'N17.0': 'Insuficiência renal aguda com necrose tubular',
  'N17.9': 'Insuficiência renal aguda não especificada',
  'N18.3': 'Doença renal crónica, estadio 3',
  'N18.4': 'Doença renal crónica, estadio 4',
  'N18.5': 'Doença renal crónica, estadio 5',
  'N18.6': 'Doença renal terminal',
  'N20.0': 'Cálculo do rim',
  'N39.0': 'Infecção do tracto urinário, localização não especificada',
  // Doenças neurológicas
  'G20': 'Doença de Parkinson',
  'G35': 'Esclerose múltipla',
  'G40.909': 'Epilepsia não especificada, não intratável',
  'G43.909': 'Enxaqueca não especificada, não intratável, sem estado de enxaqueca',
  'G81.90': 'Hemiplegia não especificada afectando lado não especificado',
  'G93.1': 'Lesão cerebral anóxica',
  // Traumatismos
  'S06.0X0A': 'Concussão sem perda de consciência, encontro inicial',
  'S09.90XA': 'Traumatismo não especificado da cabeça, encontro inicial',
  'S22.000A': 'Fractura de vértebra torácica não especificada, encontro inicial',
  'S32.000A': 'Fractura de vértebra lombar não especificada, encontro inicial',
  'S52.509A': 'Fractura do extremo distal do rádio, encontro inicial',
  'S72.001A': 'Fractura do colo do fémur, encontro inicial para fractura fechada',
  'T14.90': 'Traumatismo não especificado',
  // Neoplasias
  'C18.9': 'Neoplasia maligna do cólon, não especificada',
  'C34.10': 'Neoplasia maligna do lobo superior do brônquio ou pulmão, não especificado',
  'C50.911': 'Neoplasia maligna da mama direita, não especificada',
  'C61': 'Neoplasia maligna da próstata',
  'C67.9': 'Neoplasia maligna da bexiga, não especificada',
  'C79.51': 'Neoplasia maligna secundária do osso',
  'C80.1': 'Neoplasia maligna, localização não especificada',
  'Z85.040': 'História pessoal de neoplasia maligna do intestino grosso',
  // Saúde mental
  'F05': 'Delírio não induzido por álcool ou outras substâncias psicoativas',
  'F10.20': 'Dependência de álcool, não complicada',
  'F32.9': 'Episódio depressivo major não especificado',
  'F20.9': 'Esquizofrenia não especificada',
  // Outros comuns em contexto hospitalar
  'R00.0': 'Taquicardia não especificada',
  'R00.1': 'Bradicardia não especificada',
  'R04.2': 'Hemoptise',
  'R07.9': 'Dor torácica não especificada',
  'R10.9': 'Dor abdominal não especificada',
  'R11.2': 'Náuseas e vómitos',
  'R17': 'Icterícia não especificada',
  'R18.0': 'Ascite maligna',
  'R41.3': 'Outras amnésias',
  'R55': 'Síncope e colapso',
  'R57.0': 'Choque cardiogénico',
  'R57.1': 'Choque hipovolémico',
  'R65.10': 'Síndrome de resposta inflamatória sistémica de origem infecciosa',
  'R65.20': 'Sepsis grave sem choque séptico',
  'R65.21': 'Sepsis grave com choque séptico',
  // Procedimentos / pós-operatório
  'T81.10XA': 'Choque pós-procedimento não especificado, encontro inicial',
  'T81.30XA': 'Deiscência de ferida cirúrgica não especificada, encontro inicial',
  'T81.4XXA': 'Infecção após procedimento não especificada, encontro inicial',
};
