import { StyleSheet } from 'react-native';

export const shared = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20 },
  modalSheetTall: { maxHeight: '85%' as any },
  sheetCabecalho: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sheetTitulo: { fontSize: 18, fontWeight: '700' as const, color: '#1e293b' },
  fecharTexto: { fontSize: 18, color: '#94a3b8', fontWeight: '700' as const },
  formLabel: { fontSize: 13, fontWeight: '600' as const, color: '#475569', marginTop: 12, marginBottom: 6 },
  formInput: { borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 8, padding: 10, fontSize: 14, color: '#334155', backgroundColor: '#f8fafc' },
  modalBotoes: { flexDirection: 'row', gap: 10, marginTop: 20 },
  cancelarBotao: { flex: 1, paddingVertical: 12, borderRadius: 10, backgroundColor: '#e2e8f0', alignItems: 'center' as const },
  cancelarTexto: { fontWeight: '600' as const, color: '#64748b', fontSize: 14 },
  submeterBotao: { flex: 2, paddingVertical: 12, borderRadius: 10, backgroundColor: '#2563eb', alignItems: 'center' as const },
  submeterDesativado: { backgroundColor: '#93c5fd' },
  submeterTexto: { fontWeight: '700' as const, color: '#fff', fontSize: 14 },
  secaoHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  secaoTitulo: { fontSize: 13, fontWeight: '700' as const, color: '#475569', textTransform: 'uppercase' as const, letterSpacing: 0.5 },
  secaoAcoes: { flexDirection: 'row', gap: 6 },
  iconBotao: { width: 32, height: 32, borderRadius: 8, backgroundColor: '#e2e8f0', alignItems: 'center' as const, justifyContent: 'center' as const },
  iconBotaoAzul: { backgroundColor: '#2563eb' },
  iconBotaoTexto: { fontSize: 15 },
  iconBotaoTextoAzul: { color: '#fff', fontWeight: '700' as const, fontSize: 20, lineHeight: 24 },
  infoCard: { backgroundColor: '#fff', borderRadius: 12, padding: 14, marginBottom: 8 },
  infoLabel: { fontSize: 12, color: '#94a3b8', fontWeight: '600' as const, textTransform: 'uppercase' as const, letterSpacing: 0.5, marginBottom: 6 },
  infoValor: { fontSize: 15, color: '#1e293b', fontWeight: '500' as const, marginTop: 2 },
  vazioTexto: { color: '#94a3b8', fontSize: 14, textAlign: 'center' as const, padding: 20 },
  historicoItem: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  historicoDescricao: { fontSize: 14, color: '#334155', fontWeight: '500' as const },
  historicoMeta: { fontSize: 12, color: '#94a3b8', marginTop: 3 },
});
